apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qmqy1w4xu-java-springboot
  janus-idp.io/tekton: qmqy1w4xu-java-springboot
  backstage.io/kubernetes-id: qmqy1w4xu-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qmqy1w4xu-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
